// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// parse_solution.cpp
cpp11::list parse_solution_bins(std::string path_prefix);
extern "C" SEXP _teems_parse_solution_bins(SEXP path_prefix) {
  BEGIN_CPP11
    return cpp11::as_sexp(parse_solution_bins(cpp11::as_cpp<cpp11::decay_t<std::string>>(path_prefix)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_teems_parse_solution_bins", (DL_FUNC) &_teems_parse_solution_bins, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_teems(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
