# Generated by cpp11: do not edit by hand

parse_solution_meta <- function(path_prefix) {
  .Call(`_teems_parse_solution_meta`, path_prefix)
}

parse_solution_bins <- function(path_prefix, names_filter) {
  .Call(`_teems_parse_solution_bins`, path_prefix, names_filter)
}
