# Generated by cpp11: do not edit by hand

agg_array_sum <- function(x, codes, out_sizes) {
  return(.Call(`_teems_agg_array_sum`, x, codes, out_sizes))
}

har_split_records <- function(cf) {
  return(.Call(`_teems_har_split_records`, cf))
}

har_payload_concat <- function(records, offset) {
  return(.Call(`_teems_har_payload_concat`, records, offset))
}

har_payload_f32 <- function(records, offset, n) {
  return(.Call(`_teems_har_payload_f32`, records, offset, n))
}

har_payload_i32 <- function(records, offset, n) {
  return(.Call(`_teems_har_payload_i32`, records, offset, n))
}

har_spse_fill <- function(records, offset, n) {
  return(.Call(`_teems_har_spse_fill`, records, offset, n))
}

har_fixed_width_strings <- function(bytes, width, trim) {
  return(.Call(`_teems_har_fixed_width_strings`, bytes, width, trim))
}

parse_solution_meta <- function(path_prefix) {
  return(.Call(`_teems_parse_solution_meta`, path_prefix))
}

parse_solution_bins <- function(path_prefix, names_filter) {
  return(.Call(`_teems_parse_solution_bins`, path_prefix, names_filter))
}

parse_coefficients <- function(path_prefix, names_filter, read_values) {
  return(.Call(`_teems_parse_coefficients`, path_prefix, names_filter, read_values))
}
