#' @title Configure and solve model
#' @export
#' @description Calls the
#'   \href{https://github.com/teemsphere/teems-solver}{teems-solver}
#'   Docker image to solve the constrained optimization problem.
#'   Runs singularity, accuracy, and error checks on the results
#'   and structures outputs with [`ems_compose()`].
#' @param cmf_path Character length 1, path to the CMF file
#'   generated by [`ems_deploy()`].
#' @param solution_method The solution method to be used, default
#'   is `"Gragg"` with `steps = c(2L, 4L, 8L)`. Choices:
#'   * `"Gragg"`: Gragg's method (the smoothed modified midpoint
#'   method; Pearson 1991). The shock is applied over a sequence
#'   of linearized steps — an Euler first step, midpoint
#'   "leapfrog" steps, and a terminal smoothing pass — and the
#'   sequence is repeated for each of the three step counts in
#'   `steps`. The three solutions are then combined by Richardson
#'   extrapolation, giving rapid error decay as steps increase
#'   plus an accuracy estimate from the agreement between levels.
#'   Recommended whenever accuracy matters. See also:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd3.12.2}{GEMPACK
#'   solution methods}
#'   * `"Johansen"`: The one-step Johansen method is fast however it
#'   should only be used as a rough approximation due to handling of
#'   nonlinear equations. See:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd1.2.13}{Johansen}
#'   * `"Euler"`: The forward Euler method, computed for each of
#'   the three step counts in `steps` and combined by Richardson
#'   extrapolation. Converges more slowly than `"Gragg"` (its
#'   truncation error shrinks linearly in the step size, so the
#'   extrapolated accuracy gains one order per solution instead of
#'   two) but it is the most robust of the multistep methods: each
#'   step uses only the current state, so it tolerates
#'   near-asymptote levels and severe shocks — including exact
#'   `-100%` shocks — where the midpoint family can become
#'   unstable. Any strictly increasing step counts are permitted.
#'   * `"RK2"`, `"RK4"`: Explicit Runge-Kutta methods (the midpoint
#'   method and the classic fourth-order method; Schiffmann 2022).
#'   A single solution is computed with the one step count in
#'   `steps` — no Richardson extrapolation — with each step built
#'   from 2 (`"RK2"`) or 4 (`"RK4"`) staged linear solves. `"RK4"`
#'   reaches a given accuracy in far fewer steps than the
#'   extrapolating methods.
#'   * `"BoSha32"`, `"DoPri54"`: Embedded Runge-Kutta pairs
#'   (Bogacki-Shampine 3(2), 4 stages; Dormand-Prince 5(4), 7
#'   stages). Alongside the solution they compute a
#'   component-by-component estimate of the cumulative error —
#'   returned as the `error_estimate` column by [`ems_compose()`]
#'   and summarized as a face value in the solver log — and they
#'   support adaptive step-size control via `adaptive` and
#'   `eps_tolerance`. `"DoPri54"` with `adaptive = "yes"` is the
#'   recommended high-accuracy choice.
#' @param matrix_method Character of length 1, matrix solution
#'   method (default is `"LU"`). Choices:
#'   * `"LU"`: Standard LU decomposition, the most robust and
#'   potentially slowest for a large model. For use with both
#'   static and dynamic models.
#'   * `"DBBD"`: Doubly bordered block diagonal, parallel solution
#'   for static models partitioned by their regional set.
#'   * `"SBBD"`: Singly bordered block diagonal, parallel solution
#'   for intertemporal models partitioned along the time chain.
#'   * `"NDBBD"`: Nested doubly bordered block diagonal, for
#'   intertemporal models whose `"SBBD"` host copy does not fit the
#'   memory available.
#'   [`ems_probe()`] recommends the method and the tasks, threads
#'   and scratch to run it with for a deployment and a machine, and
#'   prints the call to paste (see Details).
#' @param ... Additional named solver arguments; anything else is an
#'   error, never a silently ignored flag. Three groups are accepted:
#'   the Runge-Kutta step controls (`adaptive`, `eps_tolerance`,
#'   `max_retries`, `retry_adjust`; see [`ems_RK()`] for their
#'   documentation and RK-tuned defaults); the MA48 workspace initial
#'   guesses `laA`, `laD` and `laDi` (integer percents of the system
#'   nonzeros — `laA` for `"LU"`/`"SBBD"` and the diagonal blocks,
#'   `laD` for the `"DBBD"`/`"NDBBD"` interface systems, `laDi` for
#'   `"NDBBD"` intermediate interfaces; when omitted, a previous run
#'   of the same deployment warm-starts them from its recorded
#'   `la_used` in `sol.stats.json`, else package defaults apply, and
#'   the solver grows the workspace itself if any guess proves too
#'   small); and the expert solver flags `postsim` (logical; `FALSE`
#'   skips the TAB's `PostSim` sections, a TEEMS-only switch with no
#'   GEMPACK counterpart), `inmemory` (logical: keep
#'   value arrays and block factors resident in memory rather than
#'   in scratch files; absent, the solver applies its per-method
#'   default, in-memory for every method except `"NDBBD"`, and falls
#'   back to scratch with a warning when the estimated need exceeds
#'   the memory available), `fastrefac` (persistent-pivot
#'   refactorization, logical), `gpzerodivide` (GEMPACK dual-class
#'   ZERODIVIDE semantics, logical), `cntl_3`/`cntl_6` (HSL
#'   pivot/ordering thresholds, numeric), `nsbbdblocks` (SBBD
#'   block-count override, integer), `withmc66` (MC66 row ordering
#'   for SBBD, logical), `smllthreads` (OpenMP threads for small
#'   sections, integer), `tempdir` (container-side scratch directory,
#'   character), `nowrites` (skip the solver-side output-file
#'   dumps, logical; coefficient composition then has nothing to read
#'   — distinct from `suppress_outputs`, which only skips the R-side
#'   composition) and `condest` (per-solve quality diagnostics on the
#'   `"LU"` matrix method, logical: componentwise backward error and
#'   scaled condition numbers via HSL MA60/MC71, logged per linear
#'   solve with run maxima recorded under `condest` in
#'   `sol.stats.json`; diagnostic-only — solutions are unchanged —
#'   and informative only for nonzero shocks), and `ma48u` (MA48/HSL_MP48
#'   pivot threshold `CNTL(2)`, numeric in (0, 1]; absent = each
#'   library's default, MA48 0.1 and MP48 0.01 — a calibration knob,
#'   not a tuning recommendation). Effective values of recorded flags
#'   land in `sol.stats.json` regardless of how they were passed.
#' @param n_threads Integer length 1 (default `1L`), OpenMP threads
#'   per MPI task. Results with more than one thread are numerically
#'   equivalent but not bit-reproducible across thread counts
#'   (parallel reduction order).
#' @param precision Character length 1, `"single"` (default) or
#'   `"double"`: floating-point precision of the solver's coefficient
#'   storage. `"single"` halves memory traffic and suffices for
#'   ordinary step counts. `"double"` selects the double-precision
#'   solver binary shipped in the same image, removing the
#'   single-precision update-rounding floor that deep extrapolation
#'   ladders and many-step large-shock runs otherwise converge onto
#'   (per-pass rounding accumulates with step count, so beyond the
#'   floor extra steps stop helping). Roughly doubles
#'   coefficient-array memory. The effective precision is recorded in
#'   `sol.stats.json` and the model diagnostics solve record.
#' @param n_tasks Integer length 1 (default is `1L`), number of
#'   tasks to run in parallel. Must be `1L` if `"matrix_method"`
#'   == "LU".
#' @param verbosity Integer length 1, `0`, `1` (default) or `2`.
#'   Solver log detail: `0` restricts output to errors, warnings, and
#'   the accuracy summary; `1` adds phase progress and timings;
#'   `2` adds per-rank and per-block debug detail.
#' @details Nothing is chosen for you here: the run is exactly the
#'   arguments given, so it is reproducible from its record on any
#'   machine. [`ems_probe()`] makes the choice explicit instead: it
#'   measures the deployed system's structure, reads the container's
#'   cores and memory (or the ones passed for another machine) and
#'   prints a recommended `matrix_method`, `n_tasks` and `n_threads`
#'   with the evidence, the memory estimate and the call to paste.
#'   The rules it applies were measured on the 2026-09 laptop ladder
#'   (12 GB, 4 and 8 cores) and the top-end cells: `"SBBD"` for every
#'   intertemporal model (fastest at every measured size, 2.4 to 230
#'   million equations; ranks to the knee of four to eight, threads
#'   for the remaining cores), `"NDBBD"` on one rank only where SBBD's
#'   host copy would not fit; `"DBBD"` at two tasks for an uncondensed
#'   static system with a usable partition (faster than LU at every
#'   rung from 346 thousand to 7.7 million equations) and for a
#'   condensed one from about 120 thousand condensed equations (70
#'   thousand under Johansen), where threaded `"LU"` stops winning;
#'   `"LU"` with up to eight threads otherwise. A bare
#'   `ems_solve(cmf_path)` runs `"LU"` on one task and one thread,
#'   which is correct for every model and slow for a large
#'   intertemporal one.
#'
#'   Before any run starts, its peak memory is estimated and compared
#'   with the container's memory (Docker Desktop's Resources setting
#'   on a laptop, the cgroup limit or the machine elsewhere, read once
#'   per session from inside the image): a run whose estimate exceeds
#'   the memory by more than the model's error band is refused by
#'   name with the estimate, the limit and the remedies; one inside
#'   the band is warned about. The memory model is peak GB per
#'   plain-equivalent equation (the solved system plus the backsolved
#'   elements, since condensation cuts equations twentyfold but not
#'   peak memory): LU about 0.9 kB, DBBD 0.85 + 0.27 per rank kB
#'   (1.55 times that when condensed), SBBD 0.36 + 0.02 per rank kB,
#'   NDBBD 0.15 per rank kB; measured on whole containers under Gragg,
#'   conservative by up to a quarter on small systems.
#'
#'   Condensation interacts with that choice. Backsolving (see the
#'   `backsolve` argument of [`ems_model()`]) substitutes variables
#'   out of the system, which densifies the diagonal blocks the
#'   bordered methods exploit: it pays under `"LU"` on static models
#'   and costs wall time everywhere else. A condensed deployment
#'   solved with a bordered method, or any condensed intertemporal
#'   deployment, is flagged at run time.
#'
#'   The MA48 workspace sizes (`laA`, `laD`, `laDi`) never need
#'   manual tuning: the solver reallocates and retries on a
#'   too-small workspace, logging each growth, and records the
#'   effective sizes as `la_used` in `sol.stats.json`, which later
#'   runs of the same deployment reuse as their starting point. Pass
#'   them through `...` only to pin a specific starting size.
#' @param suppress_outputs Logical length 1 (default is `FALSE`).
#'   When `TRUE` solver outputs are not automatically converted
#'   into structured data with [`ems_compose()`].
#' @param terminal_run Logical length 1 (default is `FALSE`).
#'   When `TRUE`, the function is exited without running the
#'   solver. This allows the user to close any R IDE or other
#'   programs prior to running from the terminal. When `TRUE`
#'   solver outputs are not automatically converted into
#'   structured data with [`ems_compose()`].
#' @param assertions Character length 1, `"fatal"` (default),
#'   `"warn"` or `"off"`. Severity of TAB `Assertion` statement
#'   failures (GEMPACK manual 25.3):
#'   `"warn"` reports and continues, `"off"` skips the checks.
#' @param range_test_initial Character length 1, `"warn"` (default),
#'   `"fatal"` or `"off"`. Severity of declared-range violations
#'   (e.g. `(ge 0)`) on initial values (GEMPACK manual 25.4.4,
#'   `range test initial values`; GEMPACK's `yes`/`warn`/`no` are
#'   `"fatal"`/`"warn"`/`"off"` here).
#' @param range_test_updated Character length 1, `"warn"` (default),
#'   `"fatal"` or `"off"`. As `range_test_initial`, for updated
#'   values (`range test updated values`).
#' @param complementarity A `teems_complementarity` object built by
#'   [`ems_complementarity()`] (default is `NULL`), run controls for
#'   models with active `Complementarity` statements (GEMPACK manual
#'   ch. 51). `NULL` applies the solver defaults; ignored by the
#'   solver when the model has no active complementarity component.
#' @seealso [`ems_deploy()`] for generating `"cmf_path"`.
#'   [`solve_in_situ()`] for calling the solver on existing input
#'   files. [`ems_compose()`] for structuring data when
#'   `"suppress_outputs"` or `"terminal_run"` is `TRUE`.
#' @return A tibble of model output variables and coefficients.
#'   `invisible(NULL)` if `suppress_outputs = TRUE`. Instructions
#'   for terminal execution if `terminal_run = TRUE`.
#' @references Pearson, K.R. (1991), "Solving Nonlinear Economic
#'   Models Accurately via a Linear Representation", Impact
#'   Project Preliminary Working Paper No. IP-55, Monash
#'   University (revised June 2002).
#'
#'   Schiffmann, F. (2022), "Runge Kutta integrators for fast and
#'   accurate solutions in GEMPACK".
#' @examples
#' \dontrun{
#' # The following examples require the teems solver to be built. 
#' # See https://teemsphere.github.io/ to get started.
#'  
#' # Solving a static model with Gragg 2-4-8 (the default):
#' ems_solve(cmf_path)
#'
#' # A quick one-step approximation:
#' ems_solve(cmf_path, solution_method = "Johansen")
#' 
#' # Solving a dynamic model with the SBBD method:
#' ems_solve(cmf_path,
#'           solution_method = "Gragg",
#'           matrix_method = "SBBD",
#'           n_tasks = 6)
#' }
ems_solve <- function(cmf_path,
                      solution_method = c("Gragg", "Johansen", "Euler", "RK2", "Heun", "RK4", "BoSha32", "DoPri54"),
                      matrix_method = c("LU", "DBBD", "SBBD", "NDBBD"),
                      n_subintervals = 1L,
                      steps = NULL,
                      n_tasks = 1L,
                      n_threads = 1L,
                      precision = c("single", "double"),
                      verbosity = 1L,
                      suppress_outputs = FALSE,
                      terminal_run = FALSE,
                      assertions = c("fatal", "warn", "off"),
                      range_test_initial = c("warn", "fatal", "off"),
                      range_test_updated = c("warn", "fatal", "off"),
                      complementarity = NULL,
                      ...
) {
if (missing(cmf_path)) {
  .cli_missing(cmf_path)
}
call <- match.call()
# Named extras ride through the dots: the Runge-Kutta step controls
# (ems_RK() is the documented front end), the MA48 workspace initial
# guesses and the expert solver flags. Anything else here is an
# error, never silently ignored.
rk_args <- list(
  adaptive = c("no", "yes", "accuracy-only"),
  eps_tolerance = 0.01,
  max_retries = 3L,
  retry_adjust = 0.5
)
xtr_args <- .solver_extra_args()
dots <- list(...)
unknown_args <- setdiff(names(dots), c(names(rk_args), names(xtr_args)))
if (length(dots) &&
  (is.null(names(dots)) || !all(nzchar(names(dots))) || length(unknown_args))) {
  if (!length(unknown_args)) unknown_args <- "<unnamed>"
  .cli_action(solve_err$solver_dots,
    action = c("abort", "inform"),
    call = call
  )
}
for (nm in names(dots)) {
  if (nm %in% names(rk_args)) {
    rk_args[nm] <- dots[nm]
  } else {
    xtr_args[nm] <- dots[nm]
  }
}
args_list <- c(mget(setdiff(names(formals()), "...")), rk_args, xtr_args)
output <- .implement_solve(
  args_list = args_list,
  call = call
)
if (is.null(output)) invisible(output) else output
}
