#' Load and prepare data inputs
#'
#' Loads GTAP HAR files, aggregates basedata and parameters
#' according to set mappings, and returns prepared data for
#' [`ems_deploy()`].
#'
#' @param dat_input Character vector of length 1, file name in
#'   working directory or path to a data input containing
#'   basedata coefficient data (e.g., a HAR file), or the
#'   corresponding "dat" list object generated by
#'   [`GTAP_convert()`].
#' @param par_input Character vector of length 1, file name in
#'   working directory or path to a data input containing
#'   parameter coefficient data (e.g., a HAR file), or the
#'   corresponding "par" list object generated by
#'   [`GTAP_convert()`].
#' @param set_input Character vector of length 1, file name in
#'   working directory or path to a data input containing set
#'   elements and attributes (e.g., a HAR file), or the
#'   corresponding "set" list object generated by
#'   [`GTAP_convert()`].
#' @param time_steps Integer vector of variable length with
#'   initial value 0 or reference year corresponding to database
#'   employed (default is `NULL`). Input format can be either the
#'   chronological years of steps including initial reference
#'   year or steps from t0.
#' @param ... A named pairlist assigning set mappings to model
#'   sets that are read in (not constructed via any set operation
#'   defined in the model file). Set mappings can be selected
#'   from a range of internally available options or provided by
#'   the user.
#'   * Internal mapping: character vector of length 1
#'   corresponding to an internally available mapping
#'   * User-provided mapping: Character vector of length 1, file
#'   name in working directory or path to a .csv file; a data
#'   frame or data frame extension (e.g., tibble, data.table).
#' 
#'   See
#'   \href{https://github.com/teemsphere/teems-mappings}{teems-mappings}
#'   for internally available mappings and formatting for
#'   user-provided mappings.
#'
#' @details
#'   Set names passed via `...` must match set names as they
#'   appear in the database. Only sets requiring aggregation need
#'   to be specified — unspecified sets whose elements are fully
#'   covered by a provided mapping are derived automatically. Any
#'   elements not covered by any provided mapping are passed
#'   through without aggregation.
#'
#' @return A list of data.tables ready for input into the
#'   `".data"` argument of [`ems_deploy()`]
#'
#' @seealso [`ems_deploy()`] for using the output of this
#'   function. [`GTAP_convert()`] for converting between GTAP
#'   v6.2 and v7.0 data formats.
#' 
#' @examples
#' \dontrun{
#' # Static model
#' v7_data <- ems_data("v7_data/gsdfdat.har",
#'                     "v7_data/gsdfpar.har",
#'                     "v7_data/gsdfset.har",
#'                     REG = "AR5",
#'                     ACTS = "food",
#'                     ENDW = "labor_diff")
#'                      
#' # Intertemporal model (explicit time steps)
#' int_data <- ems_data("v6_data/gsddat.har",
#'                      "v6_data/gsdpar.har",
#'                      "v6_data/gsdset.har",
#'                      REG = "WB23",
#'                      PROD_COMM = "services",
#'                      ENDW_COMM = "labor_agg",
#'                      time_steps = c(0, 1, 2, 4, 6, 8, 10, 15))
#'  
#' # Intertemporal model (chronological time steps)
#' int_data <- ems_data("v7_data/gsdfdat.har",
#'                      "v7_data/gsdfpar.har",
#'                      "v7_data/gsdfset.har",
#'                      REG = "R32",
#'                      ACTS = "medium",
#'                      ENDW = "labor_diff",
#'                      time_steps = c(2023, 2025, 2027, 2030, 2035))                       
#' }           
#' @export
ems_data <- function(dat_input,
                     par_input,
                     set_input,
                     time_steps = NULL,
                     ...
) {
if (missing(dat_input)) {
  .cli_missing(dat_input)
}
if (missing(par_input)) {
  .cli_missing(par_input)
}
if (missing(set_input)) {
  .cli_missing(set_input)
}
args_list <- mget(names(formals()))
args_list$set_mappings <- list(...)
call <- match.call()
.data <- .implement_data(
  args_list = args_list,
  call = call
)
.data
}