#' @title Write teems example models and scripts to file
#' @export
#' @description The teems package includes example models and
#'   scripts. This function facilitates access to both, allowing
#'   new users to immediately peruse compatible models or
#'   generate scripts containing a range of package features.
#' @return For `type = "model_files"`: a named character vector
#'   with elements `model_file` and `closure_file`. For `type =
#'   "scripts"`: a character vector of paths to the written
#'   script files.
#' @param model Character vector of length 1, name of model.
#'   Options include:
#'   * `"GTAP-RE"`: GTAP Rational Expectations
#'   * `"GTAP-INT"`: GTAP Intertemporal
#'   * `"GTAPv7"`: Standard GTAP model
#'   * `"GTAPv6"`: Classic GTAP model
#' @param path Character vector of length 1. Directory where
#'   files will be written.
#' @param type Character vector of length 1, (default is
#'   `"model_files"`). Determines the example output. Options
#'   include:
#'   * `"model_files"`: Model file and closure file
#'   * `"scripts"`: Example scripts for the chosen `model`.
#'   `dat_input`, `par_input`, and `set_input` are required.
#' @param dat_input Character vector of length 1 (default is
#'   `NULL`, only used when `type = "scripts"`),, file name in
#'   working directory or path to a data input containing
#'   basedata coefficient data, or the corresponding "dat" list
#'   object generated by [`GTAP_convert()`].
#' @param par_input Character vector of length 1 (default is
#'   `NULL`, only used when `type = "scripts"`),, file name in
#'   working directory or path to a data input containing
#'   parameter coefficient data, or the corresponding "par" list
#'   object generated by [`GTAP_convert()`].
#' @param set_input Character vector of length 1 (default is
#'   `NULL`, only used when `type = "scripts"`),, file name in
#'   working directory or path to a data input containing set
#'   elements and attributes, or the corresponding "set" list
#'   object generated by [`GTAP_convert()`].
#' @examples
#' # Write GTAP-RE model files
#' ems_example("GTAP-RE", tempdir())
#'
#' \dontrun{
#' # The following example requires input data. See
#' # https://teemsphere.github.io/ to get started.
#'
#' # Generate GTAP-RE example scripts
#' ems_example(model = "GTAP-RE",
#'             path = "path/to/example/scripts",
#'             type = "scripts",
#'             dat_input = "v7data/gsdfdat.har",
#'             par_input = "v7data/gsdfpar.har",
#'             set_input = "v7data/gsdfset.har")
#' }
ems_example <- function(model,
                        path,
                        type = c("model_files", "scripts"),
                        dat_input = NULL,
                        par_input = NULL,
                        set_input = NULL
) {
if (missing(model)) {
  .cli_missing(model)
}
if (missing(path)) {
  .cli_missing(path)
}
args_list <- mget(names(formals()))
call <- match.call()
path <- .implement_exp(
  args_list = args_list,
  call = call
)
path
}