#' Configure and solve model
#'
#' @description `ems_solve()` solves the constrained optimization
#'   problem according to a range of runtime configuration
#'   options. In order to solve the model, a `teems` Docker image
#'   (\href{https://github.com/teemsphere/teems-solver}{teems-solver})
#'   must be built. Singularity, accuracy, and error checks are
#'   carried out following a successful run.
#'
#' @param cmf_path Character length 1, path to the cmf file
#'   generated by [`ems_deploy()`].
#' @param n_tasks Integer length 1 (default is `1L`), number of
#'   tasks to run in parallel. Must be `1L` if `"matrix_method"`
#'   == "LU".
#' @param n_subintervals Integer length 1 (default is `1L`),
#'   number of subintervals for the applied shock. More
#'   subintervals may alleviate accuracy issues stemming from
#'   large shock magnitudes.
#' @param matrix_method Character of length 1, matrix solution
#'   method (default is `"LU"`). Choices:
#'   * `"LU"`: Standard LU decomposition, the most robust and
#'   potentially slowest for a large model. `"n_tasks"` must be
#'   `1L` if `"matrix_method"` == "LU". For use with both static
#'   and dynamic models.
#'   * `"DBBD"`: Doubly bordered block diagonal, parallel solution
#'   method for static models. Potentially faster than `"LU"`
#'   although less robust.
#'   * `"SBBD"`: Singly bordered block diagonal, parallel solution
#'   method for intertemporal models. Potentially faster than
#'   `"LU"` although less robust.
#'   * `"NDBBD"`: Nested doubly bordered block diagonal, parallel
#'   solution method for large intertemporal models with many
#'   timesteps.
#' @param solution_method The solution method to be used, default
#'   is the "one-step" `"Johansen"`. Choices:
#'   * `"Johansen"`: The Johansen method is fast however it should
#'   only be used as a rough approximation due to handling of
#'   nonlinear equations. See:
#'   https://www.copsmodels.com/gpmanual.htm#gpd1.2.13
#'   * `"mod_midpoint"`: The modified midpoint method
#'   performs multiple passes. See:
#'   https://www.copsmodels.com/gpmanual.htm#gpd3.12.2
#' @param steps Integer length 3 (default is `c(2L, 4L, 8L)`). A
#'   vector of steps for the modified midpoint method, must be
#'   all odd or all even and length 3. Additional steps may
#'   improve accuracy for some model runs.
#' @param laA Integer length 1 (default is `300L`). The laA
#'   memory parameter for solver pertaining to matrix methods
#'   `"LU"` and `"SBBD"`. Value is in percentages. Increase
#'   gradually if prompted via "Error return from MA48B/BD
#'   because LA is ..."
#' @param laD Integer length 1 (default is `200L`). The laD
#'   memory parameter for solver pertaining to matrix methods
#'   `"DBBD"` and `"NDBBD"`. Value is in percentages. Increase
#'   gradually if prompted via "Error return from MA48B/BD
#'   because LA is ..."
#' @param laDi Integer length 1 (default is `500L`). The laDi
#'   memory parameter for solver pertaining to matrix method
#'   `"NDBBD"`. Value is in percentages. Increase gradually if
#'   prompted via "Error return from MA48B/BD because LA is ..."
#' @param suppress_outputs Logical length 1 (default is `FALSE`).
#'   When `TRUE` solver outputs are not automatically converted
#'   into structured data with [`ems_compose()`].
#' @param terminal_run Logical length 1 (default is `FALSE`).
#'   When `TRUE`, the function is exited without running the
#'   solver. This allows the user to close any R IDE or other
#'   programs prior to running from the terminal. When `TRUE`
#'   solver outputs are not automatically converted into
#'   structured data with [`ems_compose()`].
#'
#' @examples
#' \dontrun{
#' # See \href{https://github.com/teems-org/teems-scripts}{teems-scripts}
#' # for a range of solution options.
#' }
#'
#' @return A tibble containing model output variables and
#'   coefficients. Alternatively, if `"suppress_outputs"` is
#'   `TRUE`, no return value. Alternatively, if `"terminal_run"`
#'   is `TRUE`, instructions for running the model and
#'   structuring outputs.
#' @export
ems_solve <- function(cmf_path,
                      n_tasks = 1L,
                      n_subintervals = 1L,
                      matrix_method = c("LU", "DBBD", "SBBD", "NDBBD"),
                      solution_method = c("Johansen", "mod_midpoint"),
                      steps = c(2L, 4L, 8L),
                      laA = 300L,
                      laD = 200L,
                      laDi = 500L,
                      suppress_outputs = FALSE,
                      terminal_run = FALSE
) {
args_list <- mget(names(formals()))
call <- match.call()
if (missing(cmf_path)) {
  .cli_missing(cmf_path)
}
output <- .implement_solve(
  args_list = args_list,
  call = call
)
output
}
