#' Consolidate and write all model inputs
#'
#' Validates all data and model inputs, processes shocks and
#' closure swaps, and writes the input files required by
#' [`ems_solve()`].
#'
#' @param .data A list of data.tables generated by
#'   [`ems_data()`].
#' @param model A tibble generated by [`ems_model()`].
#' @param shock A `shock` object or list of `shock` objects
#'   produced by [`ems_uniform_shock()`], [`ems_custom_shock()`],
#'   or [`ems_scenario_shock()`]. When `NULL` (default), no shock
#'   is applied and base data is returned.
#' @param swap_in A variable name string, [`ems_swap()`] object,
#'   or list of any combination thereof. Variables to be made
#'   exogenous (default `NULL`).
#' @param swap_out A variable name string, [`ems_swap()`] object,
#'   or list of any combination thereof. Variables to be made
#'   endogenous (default `NULL`).
#' @param write_dir Path to the base directory where a `teems/`
#'   subdirectory will be created for input files and solver
#'   output. Defaults to a session-scoped cache cleared on exit;
#'   specify a path for persistent output.
#' @param shock_file Path to a file with ".shf" extension
#'   representing a fully prepared shock file (default `NULL`).
#'   No checks or modifications are applied to this file.
#'
#' @return Path to the CMF file, passed to [`ems_solve()`].
#'
#' @seealso [`ems_data()`]. [`ems_model()`].
#'   [`ems_uniform_shock()`]. [`ems_custom_shock()`].
#'   [`ems_scenario_shock()`]. [`ems_swap()`]. [`ems_solve()`].
#'
#' @examples
#' \dontrun{
#' # Uniform shock with a full variable closure swap
#' shock <- ems_uniform_shock("qfd", value = 1)
#'
#' cmf_path <- ems_deploy(
#'   .data = dat,
#'   model = model,
#'   shock = shock,
#'   swap_in = "qfd",
#'   swap_out = "tfd",
#'   write_dir = "~/my_project/output"
#' )
#' 
#' # Uniform shock with multiple heterogeneous swaps 
#' yp_row <- ems_swap("yp", REGr = "row")
#' dppriv_row <- ems_swap("dppriv", REGr = "row")
#'
#' cmf_path <- ems_deploy(
#'  .data = dat,
#'  model = model,
#'  shock = shock,
#'  swap_in = list(yp_row, "qfd"),
#'  swap_out = list(dppriv_row, "tfd")
#' )
#' }
#'
#' @export
ems_deploy <- function(.data,
                       model,
                       shock = NULL,
                       swap_in = NULL,
                       swap_out = NULL,
                       write_dir = tools::R_user_dir("teems", "cache"),
                       shock_file = NULL
) {
if (missing(.data)) {
  .cli_missing(.data)
}
if (missing(model)) {
  .cli_missing(model)
}
call <- match.call()
args_list <- mget(names(formals()))
cmf_path <- .finalize(
  args_list = args_list,
  call = call
)
cmf_path
}