#' @title Load and prepare data inputs
#' @export
#' @description Loads input files, aggregates basedata and
#'   parameters according to set mappings, and returns prepared
#'   data for [`ems_deploy()`]. Accepts GTAP HAR files and
#'   objects generated by [`GTAP_convert()`] as inputs.
#' @return A list of data.tables ready for input into the `.data`
#'   argument of [`ems_deploy()`]
#' @param dat_input Character vector of length 1, file name in
#'   working directory or path to a data input containing
#'   basedata coefficient data, or the corresponding "dat" list
#'   object generated by [`GTAP_convert()`].
#' @param par_input Character vector of length 1, file name in
#'   working directory or path to a data input containing
#'   parameter coefficient data, or the corresponding "par" list
#'   object generated by [`GTAP_convert()`].
#' @param set_input Character vector of length 1, file name in
#'   working directory or path to a data input containing set
#'   elements and attributes, or the corresponding "set" list
#'   object generated by [`GTAP_convert()`].
#' @param time_steps Integer vector of variable length (default
#'   is `NULL`). For use with temporally dynamic models. Input
#'   format is either chronological years of steps including
#'   initial reference year corresponding to the database
#'   employed or steps from t0 with initial value 0.
#' @param ... A named pairlist assigning set mappings to model
#'   sets that are explicitly read (not constructed via any set
#'   operation defined in the model file). Set mappings can be
#'   selected from a range of internally available options or
#'   provided by the user.
#'   * Internal mapping: character vector of length 1
#'   corresponding to an internally available mapping.
#'   * User-provided mapping: character vector of length 1, file
#'   name in working directory or path to a CSV file; a data
#'   frame or data frame extension (e.g., tibble, data.table).
#'
#'   See
#'   \href{https://github.com/teemsphere/teems-mappings}{teems-mappings}
#'   for internally available mappings and formatting for
#'   user-provided mappings.
#' @details Set names passed via `...` must match set names as
#'   they appear in the database. Only sets requiring aggregation
#'   need to be specified. Unspecified sets whose elements are
#'   fully covered by a provided mapping are derived
#'   automatically. Any elements not covered by a provided
#'   mapping are passed through without aggregation.
#' @seealso [`ems_deploy()`] for using the output of this
#'   function. [`GTAP_convert()`] for converting between GTAP
#'   v6.2 and v7.0 data formats.
#' @examples
#' \dontrun{
#' # The following examples require input data. See
#' # https://teemsphere.github.io/ to get started.
#'
#' # Data for a static model using internal mappings
#' v7_data <- ems_data("v7_data/gsdfdat.har",
#'                     "v7_data/gsdfpar.har",
#'                     "v7_data/gsdfset.har",
#'                     REG = "AR5",
#'                     ACTS = "food",
#'                     ENDW = "labor_diff")
#'
#' # Data for an intertemporal model with explicit time steps
#' int_data <- ems_data("v6_data/gsddat.har",
#'                      "v6_data/gsdpar.har",
#'                      "v6_data/gsdset.har",
#'                      REG = "WB23",
#'                      PROD_COMM = "services",
#'                      ENDW_COMM = "labor_agg",
#'                      time_steps = c(0, 1, 2, 4, 6, 8, 10, 15))
#'
#' # Data for an intertemporal model with chronological time
#' # steps and a user-provided mapping for the ENDW set
#' int_data <- ems_data("v7_data/gsdfdat.har",
#'                      "v7_data/gsdfpar.har",
#'                      "v7_data/gsdfset.har",
#'                      REG = "R32",
#'                      ACTS = "medium",
#'                      ENDW = "user/endowment/mapping.csv",
#'                      time_steps = c(2023, 2025, 2027, 2030, 2035))
#' }           
ems_data <- function(dat_input,
                     par_input,
                     set_input,
                     time_steps = NULL,
                     ...
) {
if (missing(dat_input)) {
  .cli_missing(dat_input)
}
if (missing(par_input)) {
  .cli_missing(par_input)
}
if (missing(set_input)) {
  .cli_missing(set_input)
}
args_list <- mget(names(formals()))
args_list$set_mappings <- list(...)
call <- match.call()
.data <- .implement_data(
  args_list = args_list,
  call = call
)
.data
}