#' Loads, validates, and writes all model components
#'
#' @description `ems_deploy()` accumulate and checks all data and
#'   model inputs as well as writes required input files. Outputs
#'   from [`.data()`] and [`ems_model()`] are required inputs
#'   to `"data"`, `"model"` respectively.
#' 
#' @param .data A list of data.tables generated by the function
#'   [`ems_data()`] or equivalent.
#' @param model A tibble generated by the function
#'   [`ems_model()`] or equivalent.
#' @param shock A `shock` object or in the case of multiple
#'   shocks, list of objects produced by [`ems_shock()`] (default
#'   is `NULL`). In the case of `NULL`, a `NULL` shock will be
#'   carried out which effectively returns base data.
#' @param swap_in Character vector (default is `NULL`), or `swap`
#'   object created by [`ems_swap()`], or a list of any
#'   combination of character vectors and swap objects.
#'   Represents model variable or variables to be made exogenous.
#' @param swap_out Character vector (default is `NULL`), or
#'   `swap` object created by [`ems_swap()`], or a list of any
#'   combination of character vectors and swap objects.
#'   Represents model variable or variables to be made
#'   endogenous.
#' @param write_dir Character of length 1 (default is
#'   `tools::R_user_dir("teems", "cache")`), base directory where
#'   "teems" subdirectory will be created. Input files will be
#'   written and model solution will be carried out within the
#'   "teems" subdirectory. If persistence is desired, a
#'   user-provided base directory must be provided.
#' @param shock_file Character of length 1, file name in working
#'   directory or path to a csv representing the final shock file
#'   (default is `NULL`). No checks or modifications will be
#'   conducted on this file.
#'   
#' @return File path to a CMF file necessary to execute
#'   [`ems_solve()`].
#'
#' @details `ems_deploy()` consolidates all user inputs and
#'   carries out all operations necessary to run a CGE model. The
#'   output file path serves as a required input to
#'   [`ems_solve()`].
#'
#' @seealso [`ems_model()`] for generating the input to
#'   `"model"`.
#' @seealso [`ems_data()`] for generating the input to
#'   `".data"`.
#' @seealso [`ems_shock()`] for generating the input to
#'   `"shock"`.
#' @seealso [`ems_swap()`] for loading both full variable swaps
#'   as well as element-specific swaps.
#' @seealso [`ems_solve()`] for loading the output of this
#'   function.
#'
#' @examples
#' \dontrun{
#' # See \href{https://github.com/teems-org/teems-scripts}{teems-scripts}
#' # for a range of sample scripts.
#' }
#' @export
ems_deploy <- function(.data,
                       model,
                       shock = NULL,
                       swap_in = NULL,
                       swap_out = NULL,
                       write_dir = tools::R_user_dir("teems", "cache"),
                       shock_file = NULL
) {
if (missing(.data)) {
  .cli_missing(.data)
}
force(.data)
if (missing(model)) {
  .cli_missing(model)
}
force(model)
call <- match.call()
args_list <- mget(names(formals()))
metadata <- attr(.data, "metadata")
attr(metadata, "file") <- "metadata.rds"
sets <- .finalize_sets(
  sets = .data[purrr::map_lgl(.data, inherits, "set")],
  set_extract = model[model$type == "Set", ],
  coeff_extract = model[model$type == "Coefficient", ],
  time_steps = attr(.data, "time_steps"),
  reference_year = metadata$reference_year,
  call = call,
  data_call = attr(.data, "call"),
  model_call = attr(model, "call")
)
v <- .validate_deploy_args(
  a = args_list,
  sets = sets,
  model_headers = attr(model, "header"),
  call = call,
  data_call = attr(.data, "call")
)
closure <- .validate_closure(
  closure = attr(v$model, "closure"),
  sets = sets,
  var_extract = model[model$type == "Variable", ],
  call = call
)
closure <- .finalize_closure(
  swap_in = v$swap_in,
  swap_out = v$swap_out,
  closure = closure,
  closure_file = attr(v$model, "closure_file"),
  sets = sets,
  var_extract = model[model$type == "Variable", ],
  call = call
)
shocks <- .finalize_shocks(
  shock = v$shock,
  shock_file = v$shock_file,
  closure = closure,
  sets = sets,
  var_extract = model[model$type == "Variable", ]
)
.data <- .finalize_data(
  .data = .data,
  sets = sets,
  model = model,
  write_dir = write_dir,
  call = call,
  model_call = attr(model, "call")
)
tab <- .finalize_tab(model = model)
cmf <- .finalize_cmf(
  model = model,
  shock_file = attr(shocks, "file"),
  tab_file = attr(tab, "file"),
  cls_file = attr(closure, "file"),
  write_dir = v$write_dir
)
cmf_path <- .write_input_files(
  write_dir = v$write_dir,
  tab = tab,
  closure = closure,
  shocks = shocks,
  cmf = cmf,
  .data = .data,
  v_shock = v$shock,
  metadata = metadata,
  sets = sets
)
cmf_path
}
